- name: remove exist directory
  tags:
  - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}" # backend /app/ frontend /usr/share/nginx/html
    state: absent

- name: create app directory
  tags:
  - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: directory

- name: download application code
  tags:
  - deployment
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONANT }}-v2.zip
    dest: "{{ APP_LOCATION }}"
    remote_src: yes
